version: '3.8'
services:
  # "cosmosdb" is the name of the Docker Compose service, and is also used as the hostname for incoming connections
  cosmosdb:
    image: mcr.microsoft.com/cosmosdb/linux/azure-cosmos-emulator:latest
    environment:
      # Low partition count to speed startup (note: will actually create 2 partitions)
      AZURE_COSMOS_EMULATOR_PARTITION_COUNT: 1
      # Save data across starts
      AZURE_COSMOS_EMULATOR_ENABLE_DATA_PERSISTENCE: 'true'
      # Make sure the emulator lists "cosmosdb" as an alternative name in the cert
      AZURE_COSMOS_EMULATOR_ARGS: '/alternativenames=cosmosdb'
    # Keep data on the host in ./cosmosdata
    volumes:
      - type: bind
        source: ./cosmosdata
        target: /tmp/cosmos/appdata

  node-sample:
    build: .
    environment:
      # These names aren't special - they're just used in the Node app to configure the CosmosClient
      COSMOS_ENDPOINT: https://cosmosdb:8081
      # This is the publicly documented emulator key
      COSMOS_KEY: 'C2y6yDjf5/R+ob0N8A7Cgv30VRDJIWEHLM+4QDU5DE2nQ9nDuVTqobD4b8mGGyPMbIZnqyMsEcaGQy67XIw/Jw=='
